"""Code generation from a Database model.

Stable targets (correct, tested, round-trip safe):
  - ``python``      — self-contained dataclasses with working decode/encode
  - ``markdown``    — human-readable signal reference tables
  - ``json-schema`` — JSON Schema for frame payload validation

Experimental targets (generated output compiles/parses but decode stubs return 0):
  - ``c``           — C header with #defines and decode function stubs
"""
from __future__ import annotations

import json
import re
from typing import Literal

from dbckit.model.database import Database
from dbckit.model.signal import ByteOrder

CodegenTarget = Literal["c", "python", "markdown", "json-schema"]

_EXPERIMENTAL: set[str] = {"c"}


def codegen(db: Database, target: CodegenTarget) -> str:
    """Generate code/docs from *db* for the given *target*.

    Stable targets: ``python``, ``markdown``, ``json-schema``.
    Experimental (decode stubs only): ``c``.
    """
    if target == "c":
        return _gen_c(db)
    if target == "python":
        return _gen_python(db)
    if target == "markdown":
        return _gen_markdown(db)
    if target == "json-schema":
        return _gen_json_schema(db)
    raise ValueError(f"Unknown codegen target '{target}'. Choose c|python|markdown|json-schema.")


# ── C header (experimental) ───────────────────────────────────────────────────

def _gen_c(db: Database) -> str:
    lines = [
        "/* Auto-generated by dbckit — do not edit */",
        "/* EXPERIMENTAL: decode functions are stubs that return 0. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]
    for msg in db.messages.values():
        safe = _c_ident(msg.name)
        lines.append(f"/* {msg.name} (0x{msg.arbitration_id:X}, {msg.length} bytes) */")
        lines.append(f"#define {safe.upper()}_ID  0x{msg.arbitration_id:X}U")
        lines.append(f"#define {safe.upper()}_DLC {msg.length}U")
        for sig in msg.signals.values():
            lines.append(f"/* {sig.name}: start={sig.start_bit} len={sig.length} "
                         f"factor={sig.factor} offset={sig.offset} */")
            lines.append(
                f"static inline double decode_{_c_ident(msg.name)}_{_c_ident(sig.name)}"
                f"(const uint8_t *data) {{"
            )
            lines.append("    (void)data; /* TODO: bit extraction */")
            lines.append("    return 0.0;")
            lines.append("}")
        lines.append("")
    return "\n".join(lines)


# ── Python module ─────────────────────────────────────────────────────────────

_PY_HELPERS = '''\
def _le(data: bytes, start: int, n: int) -> int:
    """Extract n-bit little-endian (Intel) value starting at start_bit."""
    raw = 0
    for i in range(n):
        pos = start + i
        if pos >> 3 < len(data) and (data[pos >> 3] >> (pos & 7)) & 1:
            raw |= 1 << i
    return raw


def _be(data: bytes, start: int, n: int) -> int:
    """Extract n-bit big-endian (Motorola) value; start is the MSB bit position."""
    b, bit = start >> 3, start & 7
    raw = 0
    for i in range(n):
        if b < len(data) and (data[b] >> bit) & 1:
            raw |= 1 << (n - 1 - i)
        if bit == 0:
            bit, b = 7, b + 1
        else:
            bit -= 1
    return raw


def _pack_le(v: int, start: int, n: int, buf: bytearray) -> None:
    for i in range(n):
        if (v >> i) & 1:
            pos = start + i
            buf[pos >> 3] |= 1 << (pos & 7)


def _pack_be(v: int, start: int, n: int, buf: bytearray) -> None:
    b, bit = start >> 3, start & 7
    for i in range(n):
        if (v >> (n - 1 - i)) & 1:
            buf[b] |= 1 << bit
        if bit == 0:
            bit, b = 7, b + 1
        else:
            bit -= 1
'''


def _gen_python(db: Database) -> str:
    lines = [
        '"""Auto-generated by dbckit — do not edit."""',
        "from __future__ import annotations",
        "from dataclasses import dataclass",
        "",
        "",
        _PY_HELPERS,
    ]

    for msg in db.messages.values():
        cls = _py_class(msg.name)
        prefix = _py_ident(msg.name).upper()

        lines.append(f"# ── {msg.name} (0x{msg.arbitration_id:X}) {'─' * max(0, 50 - len(msg.name))}")
        lines.append(f"{prefix}_ID  = 0x{msg.arbitration_id:X}")
        lines.append(f"{prefix}_DLC = {msg.length}")
        lines.append("")

        # Value-table choice dicts
        for sig in msg.signals.values():
            if sig.value_table:
                dict_name = f"{prefix}_{_py_ident(sig.name).upper()}_CHOICES"
                entries = ", ".join(f"{k}: {v!r}" for k, v in sorted(sig.value_table.values.items()))
                lines.append(f"{dict_name} = {{{entries}}}")
        lines.append("")

        lines.append("@dataclass")
        lines.append(f"class {cls}:")
        if msg.comment:
            lines.append(f'    """{msg.comment}"""')
        lines.append("")

        # Fields
        for sig in msg.signals.values():
            is_float = sig.factor != 1.0 or sig.offset != 0.0
            pytype = "float" if is_float else "int"
            default = "0.0" if is_float else "0"
            tail = ""
            if sig.unit:
                tail = f"  # {sig.unit}"
            if sig.comment:
                tail = f"  # {sig.comment}"
            lines.append(f"    {_py_ident(sig.name)}: {pytype} = {default}{tail}")
        lines.append("")

        # decode
        lines.append("    @classmethod")
        lines.append(f"    def decode(cls, data: bytes) -> '{cls}':")
        decode_args = []
        for sig in msg.signals.values():
            field = _py_ident(sig.name)
            fn = "_le" if sig.byte_order == ByteOrder.little_endian else "_be"
            is_float = sig.factor != 1.0 or sig.offset != 0.0
            lines.append(f"        _r = {fn}(data, {sig.start_bit}, {sig.length})")
            if sig.is_signed:
                lines.append(f"        if _r >= {1 << (sig.length - 1)}: _r -= {1 << sig.length}")
            if is_float:
                lines.append(f"        {field} = _r * {sig.factor!r} + {sig.offset!r}")
            else:
                lines.append(f"        {field} = _r")
            decode_args.append(field)
        lines.append(f"        return cls({', '.join(f'{a}={a}' for a in decode_args)})")
        lines.append("")

        # encode
        lines.append("    def encode(self) -> bytes:")
        lines.append(f"        buf = bytearray({msg.length})")
        for sig in msg.signals.values():
            field = _py_ident(sig.name)
            fn = "_pack_le" if sig.byte_order == ByteOrder.little_endian else "_pack_be"
            is_float = sig.factor != 1.0 or sig.offset != 0.0
            if is_float:
                lines.append(f"        _r = int(round((self.{field} - {sig.offset!r}) / {sig.factor!r}))")
            else:
                lines.append(f"        _r = int(self.{field})")
            if sig.is_signed:
                lo, hi = -(1 << (sig.length - 1)), (1 << (sig.length - 1)) - 1
                lines.append(f"        _r = max({lo}, min({hi}, _r))")
                lines.append(f"        if _r < 0: _r += {1 << sig.length}")
            else:
                hi = (1 << sig.length) - 1
                lines.append(f"        _r = max(0, min({hi}, _r))")
            lines.append(f"        {fn}(_r, {sig.start_bit}, {sig.length}, buf)")
        lines.append("        return bytes(buf)")
        lines.append("")

    return "\n".join(lines)


# ── Markdown docs ─────────────────────────────────────────────────────────────

def _gen_markdown(db: Database) -> str:
    lines = ["# DBC Documentation", ""]
    if db.version:
        lines.append(f"**Version:** {db.version}  ")
    lines.append(f"**Messages:** {len(db.messages)}  ")
    lines.append(f"**Nodes:** {', '.join(db.nodes) or '(none)'}  ")
    lines.append("")

    for msg in db.messages.values():
        lines.append(f"## {msg.name} (`0x{msg.arbitration_id:X}`)")
        if msg.comment:
            lines.append(f"> {msg.comment}")
            lines.append("")
        lines.append(f"- **DLC:** {msg.length} bytes")
        lines.append(f"- **Senders:** {', '.join(msg.senders) or '(none)'}")
        if msg.cycle_time:
            lines.append(f"- **Cycle time:** {msg.cycle_time} ms")
        lines.append("")

        if msg.signals:
            lines.append("| Signal | Start | Len | Order | Signed | Factor | Offset | Unit | Receivers |")
            lines.append("|--------|-------|-----|-------|--------|--------|--------|------|-----------|")
            for sig in msg.signals.values():
                bo = "Intel" if sig.byte_order == ByteOrder.little_endian else "Motorola"
                signed = "Yes" if sig.is_signed else "No"
                rx = ", ".join(sig.receivers) or "(none)"
                lines.append(
                    f"| {sig.name} | {sig.start_bit} | {sig.length} | {bo} | {signed} "
                    f"| {sig.factor} | {sig.offset} | {sig.unit or '-'} | {rx} |"
                )
            lines.append("")

        if any(sig.value_table for sig in msg.signals.values()):
            for sig in msg.signals.values():
                if sig.value_table:
                    lines.append(f"**{sig.name} values:**")
                    for val, label in sorted(sig.value_table.values.items()):
                        lines.append(f"- `{val}` = {label}")
                    lines.append("")

    return "\n".join(lines)


# ── JSON Schema ───────────────────────────────────────────────────────────────

def _gen_json_schema(db: Database) -> str:
    schema: dict = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "CAN Frame Payloads",
        "description": f"Auto-generated from DBC version {db.version}",
        "type": "object",
        "properties": {},
    }
    for msg in db.messages.values():
        msg_schema: dict = {
            "type": "object",
            "title": msg.name,
            "description": msg.comment or "",
            "properties": {},
        }
        for sig in msg.signals.values():
            sig_schema: dict = {"title": sig.name}
            if sig.value_table:
                sig_schema["type"] = "string"
                sig_schema["enum"] = list(sig.value_table.values.values())
            else:
                sig_schema["type"] = "number"
                if sig.minimum is not None:
                    sig_schema["minimum"] = sig.minimum * sig.factor + sig.offset
                if sig.maximum is not None:
                    sig_schema["maximum"] = sig.maximum * sig.factor + sig.offset
            if sig.comment:
                sig_schema["description"] = sig.comment
            msg_schema["properties"][sig.name] = sig_schema
        schema["properties"][f"0x{msg.arbitration_id:X}"] = msg_schema
    return json.dumps(schema, indent=2)


# ── identifiers ───────────────────────────────────────────────────────────────

def _c_ident(s: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in s)


def _py_ident(s: str) -> str:
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", s)
    s = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", s)
    return "".join(c if c.isalnum() else "_" for c in s).lower()


def _py_class(s: str) -> str:
    return "".join(word[0].upper() + word[1:] for word in s.split("_") if word)
